# Routes pour l'entité Product
easy_product_homepage:
    path: /
    defaults: { _controller: EasyVentesBundle:Event:list }

easy_product_list:
    path: /product
    defaults: { _controller: EasyVentesBundle:Product:list }

easy_product_add:
    path: /product/add
    defaults: { _controller: EasyVentesBundle:Product:add }

easy_product_detail:
    path: /product/{id}
    defaults: { _controller: EasyVentesBundle:Product:detail }

easy_product_update:
    path: /product/update/{id}
    defaults: { _controller: EasyVentesBundle:Product:update }

easy_product_remove:
    path: /product/delete/{id}
    defaults: { _controller: EasyVentesBundle:Product:remove }


# Routes pour l'entité Event
easy_event_list:
    path: /event
    defaults: { _controller: EasyVentesBundle:Event:list }

easy_event_add:
    path: /event/add
    defaults: { _controller: EasyVentesBundle:Event:add }

easy_event_export:
    path: /event/export
    defaults: { _controller: EasyVentesBundle:Event:export }

easy_event_detail:
    path: /event/{id}
    defaults: { _controller: EasyVentesBundle:Event:detail }

easy_event_update:
    path: /event/update/{id}
    defaults: { _controller: EasyVentesBundle:Event:update }

easy_event_remove:
    path: /event/delete/{id}
    defaults: { _controller: EasyVentesBundle:Event:remove }


# Routes pour l'entité Category
easy_category_list:
    path: /category
    defaults: { _controller: EasyVentesBundle:Category:list }

easy_category_add:
    path: /category/add
    defaults: { _controller: EasyVentesBundle:Category:add }

easy_category_update:
    path: /category/update/{id}
    defaults: { _controller: EasyVentesBundle:Category:update }


# Routes pour l'entité ProductSale
easy_productsale_update:
    path: /productsale/update
    defaults: { _controller: EasyVentesBundle:ProductSale:update }

easy_productsale_list:
    path: /productsale/{id}
    defaults: { _controller: EasyVentesBundle:ProductSale:list }

easy_productsale_sendemailthank:
    path: /thank/{id}
    defaults: { _controller: EasyVentesBundle:ProductSale:sendEmailThank}
    
easy_event_loterie:
    path: /loterie/{id}
    defaults: { _controller: EasyVentesBundle:Event:loterie}
