<?php

namespace Easy\Bundle\VentesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEventRepository extends EntityRepository
{
}
