<?php

namespace Easy\Bundle\VentesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findUserLoterie(Event $event)
    {
        $qb = $this
            ->createQueryBuilder('u')
            ->join('u.events', 'ue', 'WITH', 'ue.event = :event')
            ->addSelect('ue')
            ->setParameter('event', $event)
            ->orderBy('u.nbevent' , 'ASC')
        ;

        return $qb->getQuery()
            ->setMaxResults($event->getNbPers())
            ->getResult()
            ;
    }
}
