easy_client_homepage:
    path:     /
    defaults: { _controller: EasyVentesBundle:User:index }

easy_client_product:
    path:   /product
    defaults: { _controller: EasyClientBundle:Product:list }

easy_client_event:
    path:   /event
    defaults: { _controller: EasyClientBundle:Event:list }
    
easy_client_update:
    path:     /user/update
    defaults: { _controller: EasyVentesBundle:User:update }

easy_client_event_inscription:
    path:   /event/inscription/{id}
    defaults: { _controller: EasyClientBundle:Event:inscription }

easy_client_event_detail:
    path:   /event/detail/{id}
    defaults: { _controller: EasyClientBundle:Event:detail }

easy_client_best:
    path: /productsale/best
    defaults: { _controller: EasyVentesBundle:ProductSale:best }

easy_client_favorite:
    path: /productsale/favorite/{id}
    defaults: { _controller: EasyVentesBundle:UserCategory:update }