easy_client_homepage:
    path:     /
    defaults: { _controller: EasyVentesBundle:User:index }

easy_client_product:
    path:   /product
    defaults: { _controller: EasyClientBundle:Product:list }

easy_client_event:
    path:   /event
    defaults: { _controller: EasyClientBundle:Event:list }

easy_client_event_inscription:
    path:   /event/inscription
    defaults: { _controller: EasyClientBundle:Event:inscription }
    
easy_ventes_update:
    path:     /user/update
    defaults: { _controller: EasyVentesBundle:User:update }